set names cp1251;

/* project */

INSERT INTO project VALUES('zodino_pns','Жодино ПНС №20');

/* object */

INSERT INTO object VALUES('zodino_pns.zodino_pns_20','zodino_pns','Жодино ПНС №20');

/* ds_list */

INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_apn_srv',2924115851,'zodino_pns.zodino_pns_20','asciz','Имя APN сервера');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_apn_user',1401658171,'zodino_pns.zodino_pns_20','asciz','Имя APN пользователя');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_apn_pass',1591108675,'zodino_pns.zodino_pns_20','asciz','APN пароль');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_tcp_srv',3242106164,'zodino_pns.zodino_pns_20','asciz','Имя TCP сервера');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_tcp_port',3325610569,'zodino_pns.zodino_pns_20','asciz','Имя TCP порта');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_object_autorization',217796252,'zodino_pns.zodino_pns_20','asciz','Имя объекта авторизации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_name_user_autorization',2378380785,'zodino_pns.zodino_pns_20','asciz','Имя пользователя авторизации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gprs_pass_autorization',610021647,'zodino_pns.zodino_pns_20','asciz','Пароль авторизации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_lvl_signal_gsm',2785329982,'zodino_pns.zodino_pns_20','uint','Уровень сигнала GSM');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_num_phone_ascii',748895418,'zodino_pns.zodino_pns_20','str','Номер телефона');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_flag_disable_sms',3889468069,'zodino_pns.zodino_pns_20','bool','Флаг запрета SMS - запрещены');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_flag_disable_sms_limiter',3516778752,'zodino_pns.zodino_pns_20','bool','Флаг запрета SMS по ограничителю  - запрещены');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_limiter_sms_messages',1167099134,'zodino_pns.zodino_pns_20','uint','Ограничитель SMS в сообщениях');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.gsm_counter_send_sms',3964450728,'zodino_pns.zodino_pns_20','uint','Счетчик отправленных SMS');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.as_time_block_alm',240480196,'zodino_pns.zodino_pns_20','uint','Время блокировки аварий, в секундах ( 0 – 3600 сек; 0 – не использовать)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.as_flag_disable_alm',3734979923,'zodino_pns.zodino_pns_20','bool','Флаг заперта обработки аварий - запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_value',1205520154,'zodino_pns.zodino_pns_20','float','Значение датчика давления воды 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_min_value',1597028080,'zodino_pns.zodino_pns_20','float','Значение минимального предела PS1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_max_value',2296054961,'zodino_pns.zodino_pns_20','float','Значение максимального предела PS1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_min_use',3990729244,'zodino_pns.zodino_pns_20','bool','Использовать минимум датчика давления воды 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_max_use',3996013139,'zodino_pns.zodino_pns_20','bool','Использовать максимум датчика давления воды 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_min_alm',896745244,'zodino_pns.zodino_pns_20','bool','Достигнут минимальный предел (0 – не достигнут) PS1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps1_max_alm',914415443,'zodino_pns.zodino_pns_20','bool','Достигнут максимальный предел (0 – не достигнут) PS1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_value',1983044999,'zodino_pns.zodino_pns_20','float','Значение датчика PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_min_value',3335704817,'zodino_pns.zodino_pns_20','float','Значение минимального предела PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_max_value',288973488,'zodino_pns.zodino_pns_20','float','Значение максимального предела PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_min_use',3562049241,'zodino_pns.zodino_pns_20','bool','Использовать анализ минимального предела (0 – не использовать) PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_max_use',3617812118,'zodino_pns.zodino_pns_20','bool','Использовать анализ максимального предела (0 – не использовать) PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_min_alm',217973721,'zodino_pns.zodino_pns_20','bool','Достигнут минимальный предел (0 – не достигнут) PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ps2_max_alm',252568470,'zodino_pns.zodino_pns_20','bool','Достигнут максимальный предел (0 – не достигнут) PS2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_time_rotation_hour',1715663209,'zodino_pns.zodino_pns_20','uint','Значение времени ротации (час)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_time_rotation_minute',336457204,'zodino_pns.zodino_pns_20','uint','Значение времени ротации (минута)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_period_rotation',3148055521,'zodino_pns.zodino_pns_20','uint','Значение периода ротации (в часах)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_p1_use_rotation',862613923,'zodino_pns.zodino_pns_20','bool','Насос 1 используется в ротации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_p2_use_rotation',1326142584,'zodino_pns.zodino_pns_20','bool','Насос 2 используется в ротации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_p3_use_rotation',3523523854,'zodino_pns.zodino_pns_20','bool','Насос 3 используется в ротации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_p4_use_rotation',3083411406,'zodino_pns.zodino_pns_20','bool','Насос 4 используется в ротации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_p5_use_rotation',717684408,'zodino_pns.zodino_pns_20','bool','Насос 5 используется в ротации');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_use_time_rotation',2237590004,'zodino_pns.zodino_pns_20','bool','Использовать ротацию по времени');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_use_rotation_via_period',1875259819,'zodino_pns.zodino_pns_20','bool','Использовать ротацию через период');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rs_need_rotation',2527204334,'zodino_pns.zodino_pns_20','bool','Необходима ротация');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reserve',886466149,'zodino_pns.zodino_pns_20','bool','Резерв');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_value',1587969281,'zodino_pns.zodino_pns_20','int','Значение датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_min_value',4144006034,'zodino_pns.zodino_pns_20','int','Значение минимального предела датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_max_value',552284627,'zodino_pns.zodino_pns_20','int','Значение максимального предела датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_min_use',1868511848,'zodino_pns.zodino_pns_20','bool','Использование минимума датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_max_use',1823267367,'zodino_pns.zodino_pns_20','bool','Использование максимума датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_min_alm',3086071656,'zodino_pns.zodino_pns_20','bool','Достигнут минимальный предел датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.ts_max_alm',3020052263,'zodino_pns.zodino_pns_20','bool','Достигнут максимальный предел датчика температуры');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_value',158865323,'zodino_pns.zodino_pns_20','uint','Насос 1. Значение тока насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_min_value',2049054915,'zodino_pns.zodino_pns_20','uint','Насос 1. Значение минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_max_value',2915674754,'zodino_pns.zodino_pns_20','uint','Насос 1. Значение максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_min_use',2530259347,'zodino_pns.zodino_pns_20','bool','Насос 1. Использовать анализ минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_max_use',2502119900,'zodino_pns.zodino_pns_20','bool','Насос 1. Использовать анализ максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_min_alm',1316895891,'zodino_pns.zodino_pns_20','bool','Насос 1. Достигнут минимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_max_alm',1301142748,'zodino_pns.zodino_pns_20','bool','Насос 1. Достигнут максимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_use_auto_off_on_event',1408485046,'zodino_pns.zodino_pns_20','bool','Насос 1. Использовать автовыключение насоса по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_on',2261361146,'zodino_pns.zodino_pns_20','bool','Насос 1. Насос включен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_state_on',2722546651,'zodino_pns.zodino_pns_20','bool','Насос 1. Состояние включения насоса - включается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_state_off',2947148919,'zodino_pns.zodino_pns_20','bool','Насос 1. Состояние выключения насоса - выключается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_value',948964662,'zodino_pns.zodino_pns_20','uint','Насос 2. Значение тока насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_min_value',3821043394,'zodino_pns.zodino_pns_20','uint','Насос 2. Значение минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_max_value',875285635,'zodino_pns.zodino_pns_20','uint','Насос 2. Значение максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_min_use',2942143830,'zodino_pns.zodino_pns_20','bool','Насос 2. Использовать анализ минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_max_use',2897112345,'zodino_pns.zodino_pns_20','bool','Насос 2. Использовать анализ максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_min_alm',2012414038,'zodino_pns.zodino_pns_20','bool','Насос 2. Достигнут минимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_max_alm',1946214425,'zodino_pns.zodino_pns_20','bool','Насос 2. Достигнут максимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_use_auto_off_on_event',622264203,'zodino_pns.zodino_pns_20','bool','Насос 2. Использовать автовыключение насоса по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_on',2491158036,'zodino_pns.zodino_pns_20','bool','Насос 2. Насос включен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_state_on',1232173272,'zodino_pns.zodino_pns_20','bool','Насос 2. Состояние включения насоса - включается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_state_off',910920310,'zodino_pns.zodino_pns_20','bool','Насос 2. Состояние выключения насоса - выключается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_value',2665940610,'zodino_pns.zodino_pns_20','uint','Насос 3. Значение тока насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_min_value',575578370,'zodino_pns.zodino_pns_20','uint','Насос 3. Значение минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_max_value',4121236291,'zodino_pns.zodino_pns_20','uint','Насос 3. Значение максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_min_use',3089537301,'zodino_pns.zodino_pns_20','bool','Насос 3. Использовать анализ минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_max_use',3151329626,'zodino_pns.zodino_pns_20','bool','Насос 3. Использовать анализ максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_min_alm',1619530773,'zodino_pns.zodino_pns_20','bool','Насос 3. Достигнут минимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_max_alm',1669067866,'zodino_pns.zodino_pns_20','bool','Насос 3. Достигнут максимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_use_auto_off_on_event',3194295647,'zodino_pns.zodino_pns_20','bool','Насос 3. Использовать автовыключение насоса по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_on',750807409,'zodino_pns.zodino_pns_20','bool','Насос 3. Насос включен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_state_on',2796753894,'zodino_pns.zodino_pns_20','bool','Насос 3. Состояние включения насоса - включается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_state_off',4156904886,'zodino_pns.zodino_pns_20','bool','Насос 3. Состояние выключения насоса - выключается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_value',1530935308,'zodino_pns.zodino_pns_20','uint','Насос 4. Значение тока насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_min_value',192263297,'zodino_pns.zodino_pns_20','uint','Насос 4. Значение минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_max_value',3701343936,'zodino_pns.zodino_pns_20','uint','Насос 4. Значение максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_min_use',3695703260,'zodino_pns.zodino_pns_20','bool','Насос 4. Использовать анализ минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_max_use',3753120915,'zodino_pns.zodino_pns_20','bool','Насос 4. Использовать анализ максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_min_alm',82409948,'zodino_pns.zodino_pns_20','bool','Насос 4. Достигнут минимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_max_alm',119183763,'zodino_pns.zodino_pns_20','bool','Насос 4. Достигнут максимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_use_auto_off_on_event',3369897457,'zodino_pns.zodino_pns_20','bool','Насос 4. Использовать автовыключение насоса по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_on',2971095496,'zodino_pns.zodino_pns_20','bool','Насос 4. Насос включен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_state_on',1148127391,'zodino_pns.zodino_pns_20','bool','Насос 4. Состояние включения насоса - включается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_state_off',3741204533,'zodino_pns.zodino_pns_20','bool','Насос 4. Состояние выключения насоса - выключается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_value',4248253368,'zodino_pns.zodino_pns_20','uint','Насос 5. Значение тока насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_min_value',3405474625,'zodino_pns.zodino_pns_20','uint','Насос 5. Значение минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_max_value',487643392,'zodino_pns.zodino_pns_20','uint','Насос 5. Значение максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_min_use',3409764511,'zodino_pns.zodino_pns_20','bool','Насос 5. Использовать анализ минимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_max_use',3369009360,'zodino_pns.zodino_pns_20','bool','Насос 5. Использовать анализ максимального предела насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_min_alm',328363423,'zodino_pns.zodino_pns_20','bool','Насос 5. Достигнут минимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_max_alm',274828752,'zodino_pns.zodino_pns_20','bool','Насос 5. Достигнут максимальный предел  насоса');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_use_auto_off_on_event',1404004133,'zodino_pns.zodino_pns_20','bool','Насос 5. Использовать автовыключение насоса по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_on',162215597,'zodino_pns.zodino_pns_20','bool','Насос 5. Насос включен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_state_on',2880267169,'zodino_pns.zodino_pns_20','bool','Насос 5. Состояние включения насоса - включается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_state_off',527474677,'zodino_pns.zodino_pns_20','bool','Насос 5. Состояние выключения насоса - выключается');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_current_task',2274697147,'zodino_pns.zodino_pns_20','float','Текущее задание');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_work_mode',2925078999,'zodino_pns.zodino_pns_20','uint','Режим работы');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_day_num',54380229,'zodino_pns.zodino_pns_20','uint','Номер дня (0-7, 0 – суточный график)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_halfhour_task',42705747,'zodino_pns.zodino_pns_20','bytes','Задание на получас');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_task',421858097,'zodino_pns.zodino_pns_20','float','Задание');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.fc_week_graph',3013548297,'zodino_pns.zodino_pns_20','bytes','Недельный график');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_set_freq',2518267838,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Задание частоты, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_set_pid',3656344787,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Задание ПИД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_address',4183409783,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Адрес устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_use_answer',1663363790,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Использовать анализ ответа устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_use',2928227916,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Использовать устройство');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_set_freq',2100169917,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Задание частоты, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_set_pid',3764541462,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Задание ПИД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_address',3235182770,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Адрес устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_use_answer',347748414,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Использовать анализ ответа устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_use',3911797916,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Использовать устройство');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_set_freq',2464966531,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Задание частоты, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_set_pid',4145630293,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Задание ПИД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_address',3618630897,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Адрес устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_use_answer',2401203281,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Использовать анализ ответа устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_use',3561579820,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Использовать устройство');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_set_freq',1882225914,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Задание частоты, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_set_pid',2474123676,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Задание ПИД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_address',3016655160,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Адрес устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_use_answer',4219968990,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Использовать анализ ответа устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_use',1718204732,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Использовать устройство');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_set_freq',2683443140,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Задание частоты, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_set_pid',2214802911,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Задание ПИД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_address',2763363707,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Адрес устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_use_answer',1612894641,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Использовать анализ ответа устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_use',1527353484,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Использовать устройство');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_value',2820350224,'zodino_pns.zodino_pns_20','float','РСМ0503. Значение текущего расхода');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_acc_value',1771400572,'zodino_pns.zodino_pns_20','uint','РСМ0503. Значение накопленного расхода');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_address',3581932243,'zodino_pns.zodino_pns_20','uint','РСМ0503. Адрес датчика');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_common_alm',4271307866,'zodino_pns.zodino_pns_20','bool','РСМ0503. Ошибка устройства ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_not_answer',3287281945,'zodino_pns.zodino_pns_20','bool','РСМ0503. Датчик не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_cs_use',1143434234,'zodino_pns.zodino_pns_20','bool','РСМ0503. Использовать датчик');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.version',2485804932,'zodino_pns.zodino_pns_20','str','Версия');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.count_reset_controller',1355581908,'zodino_pns.zodino_pns_20','uint','Количество сбросов контроллера');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_por',3917180497,'zodino_pns.zodino_pns_20','bool','Сброс POR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_bor',4141422927,'zodino_pns.zodino_pns_20','bool','Сброс BOR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_wdtr',3075773775,'zodino_pns.zodino_pns_20','bool','Сброс WDTR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_swr',1764116561,'zodino_pns.zodino_pns_20','bool','Сброс SWR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_extr',1484279887,'zodino_pns.zodino_pns_20','bool','Сброс EXTR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_iopr_or_uwr',3325221392,'zodino_pns.zodino_pns_20','bool','Сброс IOPR или UWR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.reset_trapr',2429847171,'zodino_pns.zodino_pns_20','bool','Сброс TRAPR');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.date_time',343682126,'zodino_pns.zodino_pns_20','date','Дата/время');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.step_stat',890789775,'zodino_pns.zodino_pns_20','uint','Шаг статистики');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.count_block_stat',2712941083,'zodino_pns.zodino_pns_20','uint','Количество блоков статистики');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.count_part_of_block_stat',2900841845,'zodino_pns.zodino_pns_20','uint','Количество блоков для частичного получения статистики');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.save_alm_stat',4020118688,'zodino_pns.zodino_pns_20','bool','Сохранение аварийной статистики');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.save_stat_send_sms',1558222868,'zodino_pns.zodino_pns_20','bool','Сохранение статистики по отправке SMS');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.save_stat_event',744047326,'zodino_pns.zodino_pns_20','bool','Сохранение статистики по событию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_memory',2407339418,'zodino_pns.zodino_pns_20','bool','Авария заполненности памяти для статистики');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.rsm0503_use_responce_analysis',3628715170,'zodino_pns.zodino_pns_20','bool','РСМ0503. Использовать анализ ответа датчика ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_output_freq',2461529350,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Выходная частота, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_speed_engine',468249283,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Скорость двигателя, об/мин');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_amperage_engine',1986969435,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Ток двигателя, А');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_voltage_engine',878486919,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Выходное напряжение, В');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_power_engine',3371655495,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Мощность двигателя, %');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_invertor_power_gigawatt',1849230628,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Счетчик ГВт*ч инвертера, ГВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_invertor_power_megawatt',945386392,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Счетчик МВт*ч инвертера, MВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_invertor_power_kilowatt',3965804233,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Счетчик кВт*ч инвертера, кВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_disconnecion_reason',4287323870,'zodino_pns.zodino_pns_20','uint','abb_acs580 №1. Отказ, вызвавший отключения');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_fact_value',1808539838,'zodino_pns.zodino_pns_20','float','abb_acs580 №1. Фактическое значение регулируемой величины');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_ready',985412178,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Готов к включению');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_ready_to_run',1210067109,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Готов к пуску');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_ready_for_task',1987298111,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Готов по заданию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_rejection',3790398946,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Отказ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_switch_2_inactiv',1871380463,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Выключатель 2 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_switch_3_inactiv',2029120428,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Выключатель 3 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_forbid_to_on',3322257903,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Включение запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_alert',97841468,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Предупреждение');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_drive_on_setting',3370007392,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Привод на уставке');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_remote_mode',3678446107,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Режим управление - дистанционный');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_too_high_speed_or_frequency',246191731,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Превышено ограничение скорости/частоты');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_custom1',283347611,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Пользовательский 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_custom2',2313870113,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Пользовательский 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_custom3',4277005239,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Пользовательский 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_custom4',1619623444,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Пользовательский 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_common_alm',2079726914,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Общая авария устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_not_answer',1183780865,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Устройство не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_output_freq',796760520,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Выходная частота, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_speed_engine',1737084696,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Скорость двигателя, об/мин');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_amperage_engine',636806367,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Ток двигателя, А');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_voltage_engine',496243061,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Выходное напряжение, В');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_power_engine',3029746844,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Мощность двигателя, %');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_invertor_power_gigawatt',1540666231,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Счетчик ГВт*ч инвертера, ГВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_invertor_power_megawatt',229950923,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Счетчик МВт*ч инвертера, MВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_invertor_power_kilowatt',3649890458,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Счетчик кВт*ч инвертера, кВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_disconnecion_reason',2224413757,'zodino_pns.zodino_pns_20','uint','abb_acs580 №2. Отказ, вызвавший отключения');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_fact_value',475198030,'zodino_pns.zodino_pns_20','float','abb_acs580 №2. Фактическое значение регулируемой величины');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_ready',190064847,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Готов к включению');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_ready_to_run',876678526,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Готов к пуску');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_ready_for_task',1606121421,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Готов по заданию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_rejection',2014217187,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Отказ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_switch_2_inactiv',2232165005,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Выключатель 2 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_switch_3_inactiv',2457286350,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Выключатель 3 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_forbid_to_on',3127149620,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Включение запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_alert',876407713,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Предупреждение');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_drive_on_setting',576251394,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Привод на уставке');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_remote_mode',1720372949,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Режим управление - дистанционный');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_too_high_speed_or_frequency',2879716639,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Превышено ограничение скорости/частоты');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_custom1',695121502,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Пользовательский 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_custom2',2959599588,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Пользовательский 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_custom3',3345012594,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Пользовательский 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_custom4',1493451473,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Пользовательский 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_common_alm',208195506,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Общая авария устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_not_answer',823247601,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Устройство не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_output_freq',4075503693,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Выходная частота, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_speed_engine',4203097710,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Скорость двигателя, об/мин');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_amperage_engine',2723295132,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Ток двигателя, А');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_voltage_engine',3019669732,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Выходное напряжение, В');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_power_engine',697935338,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Мощность двигателя, %');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_invertor_power_gigawatt',4267647865,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Счетчик ГВт*ч инвертера, ГВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_invertor_power_megawatt',2822723013,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Счетчик МВт*ч инвертера, MВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_invertor_power_kilowatt',2080864404,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Счетчик кВт*ч инвертера, кВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_disconnecion_reason',458186659,'zodino_pns.zodino_pns_20','uint','abb_acs580 №3. Отказ, вызвавший отключения');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_fact_value',2281160225,'zodino_pns.zodino_pns_20','float','abb_acs580 №3. Фактическое значение регулируемой величины');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_ready',2904761211,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Готов к включению');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_ready_to_run',2840521736,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Готов к пуску');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_ready_for_task',4057196124,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Готов по заданию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_rejection',3112197155,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Отказ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_switch_2_inactiv',1784583276,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Выключатель 2 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_switch_3_inactiv',2099609647,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Выключатель 3 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_forbid_to_on',661349698,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Включение запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_alert',2454446101,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Предупреждение');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_drive_on_setting',3440005347,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Привод на уставке');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_remote_mode',3139180368,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Режим управление - дистанционный');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_too_high_speed_or_frequency',3366134843,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Превышено ограничение скорости/частоты');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_custom1',1041605149,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Пользовательский 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_custom2',2803692455,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Пользовательский 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_custom3',3491480369,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Пользовательский 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_custom4',1316968082,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Пользовательский 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_common_alm',2546828253,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Общая авария устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_not_answer',2863959710,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Устройство не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_output_freq',2409121301,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Выходная частота, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_speed_engine',2672526510,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Скорость двигателя, об/мин');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_amperage_engine',2193642455,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Ток двигателя, А');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_voltage_engine',1308981393,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Выходное напряжение, В');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_power_engine',1280577322,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Мощность двигателя, %');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_invertor_power_gigawatt',806346705,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Счетчик ГВт*ч инвертера, ГВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_invertor_power_megawatt',1718593901,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Счетчик МВт*ч инвертера, MВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_invertor_power_kilowatt',2992079932,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Счетчик кВт*ч инвертера, кВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_disconnecion_reason',1923668475,'zodino_pns.zodino_pns_20','uint','abb_acs580 №4. Отказ, вызвавший отключения');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_fact_value',4084160430,'zodino_pns.zodino_pns_20','float','abb_acs580 №4. Фактическое значение регулируемой величины');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_ready',1753488885,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Готов к включению');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_ready_to_run',3431155400,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Готов к пуску');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_ready_for_task',204086825,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Готов по заданию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_rejection',2428193184,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Отказ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_switch_2_inactiv',2339413512,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Выключатель 2 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_switch_3_inactiv',2618001995,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Выключатель 3 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_forbid_to_on',1118228354,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Включение запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_alert',1475141275,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Предупреждение');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_drive_on_setting',740579975,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Привод на уставке');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_remote_mode',3329167624,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Режим управление - дистанционный');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_too_high_speed_or_frequency',986000774,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Превышено ограничение скорости/частоты');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_custom1',1517604820,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Пользовательский 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_custom2',3279789678,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Пользовательский 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_custom3',3027939064,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Пользовательский 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_custom4',706624347,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Пользовательский 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_common_alm',3814025810,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Общая авария устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_not_answer',3727451921,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Устройство не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_output_freq',1376690064,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Выходная частота, Гц');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_speed_engine',38036952,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Скорость двигателя, об/мин');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_amperage_engine',90609812,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Ток двигателя, А');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_voltage_engine',3765299456,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Выходное напряжение, В');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_power_engine',3512462940,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Мощность двигателя, %');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_invertor_power_gigawatt',2508476383,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Счетчик ГВт*ч инвертера, ГВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_invertor_power_megawatt',3286514019,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Счетчик МВт*ч инвертера, MВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_invertor_power_kilowatt',400299058,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Счетчик кВт*ч инвертера, кВт*ч');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_disconnecion_reason',3983694437,'zodino_pns.zodino_pns_20','uint','abb_acs580 №5. Отказ, вызвавший отключения');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_fact_value',1758075841,'zodino_pns.zodino_pns_20','float','abb_acs580 №5. Фактическое значение регулируемой величины');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_ready',3472037441,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Готов к включению');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_ready_to_run',1368172478,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Готов к пуску');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_ready_for_task',2722271160,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Готов по заданию');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_rejection',1362466400,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Отказ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_switch_2_inactiv',1679960297,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Выключатель 2 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_switch_3_inactiv',1935228074,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Выключатель 3 не активен');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_forbid_to_on',3752406772,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Включение запрещено');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_alert',4053521711,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Предупреждение');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_drive_on_setting',3279350886,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Привод на уставке');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_remote_mode',469354637,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Режим управление - дистанционный');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_too_high_speed_or_frequency',1505948834,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Превышено ограничение скорости/частоты');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_custom1',1292884887,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Пользовательский 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_custom2',3557198381,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Пользовательский 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_custom3',2734799547,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Пользовательский 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_custom4',1030041368,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Пользовательский 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_common_alm',2029004349,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Общая авария устройства');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_not_answer',1166617470,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Устройство не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_time_incorrect',1593906027,'zodino_pns.zodino_pns_20','bool','Время некорректно');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_water',1540062594,'zodino_pns.zodino_pns_20','bool','Затопление');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_nsd',451223071,'zodino_pns.zodino_pns_20','bool','НСД');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_power',192047352,'zodino_pns.zodino_pns_20','bool','Авария ИБП');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_block_di1_not_answer',274400339,'zodino_pns.zodino_pns_20','bool','Блок Di1 не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_block_di2_not_answer',1741018787,'zodino_pns.zodino_pns_20','bool','Блок Di2 не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_block_do1_not_answer',2965298062,'zodino_pns.zodino_pns_20','bool','Блок Do1 не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_block_rs485_1_not_answer',2056280178,'zodino_pns.zodino_pns_20','bool','Блок RS485 №1 не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.alm_block_rs485_2_not_answer',219056770,'zodino_pns.zodino_pns_20','bool','Блок RS485 №2 не отвечает');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.mode_alm_nsd',4220513355,'zodino_pns.zodino_pns_20','bool','Режим обработки НСД ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_mode',2581174199,'zodino_pns.zodino_pns_20','bool','Режим работы Н1 (1 – авто; 0 – ручной)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_mode',525198617,'zodino_pns.zodino_pns_20','bool','Режим работы Н2 (1 – авто; 0 – ручной)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_mode',3557897916,'zodino_pns.zodino_pns_20','bool','Режим работы Н3 (1 – авто; 0 – ручной)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_mode',3373532676,'zodino_pns.zodino_pns_20','bool','Режим работы Н4 (1 – авто; 0 – ручной)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_mode',38327713,'zodino_pns.zodino_pns_20','bool','Режим работы Н5 (1 – авто; 0 – ручной)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p1_minute',379512640,'zodino_pns.zodino_pns_20','uint','Наработка насоса 1(мин)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p2_minute',2551308451,'zodino_pns.zodino_pns_20','uint','Наработка насоса 2(мин)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p3_minute',1421598781,'zodino_pns.zodino_pns_20','uint','Наработка насоса 3(мин)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p4_minute',1585375524,'zodino_pns.zodino_pns_20','uint','Наработка насоса 4(мин)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p5_minute',2463427002,'zodino_pns.zodino_pns_20','uint','Наработка насоса 5(мин)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p1_hour',736576753,'zodino_pns.zodino_pns_20','uint','Наработка насоса 1(часы)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p2_hour',2910008927,'zodino_pns.zodino_pns_20','uint','Наработка насоса 2(часы)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p3_hour',1714415098,'zodino_pns.zodino_pns_20','uint','Наработка насоса 3(часы)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p4_hour',2066404674,'zodino_pns.zodino_pns_20','uint','Наработка насоса 4(часы)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.time_work_p5_hour',2960525031,'zodino_pns.zodino_pns_20','uint','Наработка насоса 5(часы)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.num_main_pump',2372509288,'zodino_pns.zodino_pns_20','uint','Номер насоса с ПЧТ (1-5)');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.correction_to_fc_task',4021136352,'zodino_pns.zodino_pns_20','float','Поправка к заданию ПЧТ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.mode_autokeep_ps',1442053233,'zodino_pns.zodino_pns_20','bool','Режим поддержания давления');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_use',1558831683,'zodino_pns.zodino_pns_20','bool','Использовать насос 1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_use',457808019,'zodino_pns.zodino_pns_20','bool','Использовать насос 2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_use',640266531,'zodino_pns.zodino_pns_20','bool','Использовать насос 3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_use',2483645747,'zodino_pns.zodino_pns_20','bool','Использовать насос 4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_use',2842248323,'zodino_pns.zodino_pns_20','bool','Использовать насос 5');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.delta_autokeep_ps',3733968460,'zodino_pns.zodino_pns_20','float','Гистерезис на автоподдержание давления');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.delay_stabilization_system_autokeep',3822164524,'zodino_pns.zodino_pns_20','uint','Таймаут на стабилизацию системы в секундах');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_off_low_frequency',1853228982,'zodino_pns.zodino_pns_20','float','нижняя  частота выключения Н2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_on_high_frequency',1334195667,'zodino_pns.zodino_pns_20','float','верхняя  частота включения Н2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_off_low_frequency',3113519086,'zodino_pns.zodino_pns_20','float','нижняя  частота выключения Н3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_on_high_frequency',2556736907,'zodino_pns.zodino_pns_20','float','верхняя  частота включения Н3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_off_low_frequency',4088007845,'zodino_pns.zodino_pns_20','float','нижняя  частота выключения Н4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_on_high_frequency',3529129664,'zodino_pns.zodino_pns_20','float','верхняя  частота включения Н4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_off_low_frequency',608734461,'zodino_pns.zodino_pns_20','float','нижняя  частота выключения Н5');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_on_high_frequency',95993496,'zodino_pns.zodino_pns_20','float','верхняя  частота включения Н5');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.freq_time_analys_sec',32426730,'zodino_pns.zodino_pns_20','uint','Время анализа частоты  в секундах');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_1_work',3440428505,'zodino_pns.zodino_pns_20','bool','abb_acs580 №1. Работа');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_2_work',1266988919,'zodino_pns.zodino_pns_20','bool','abb_acs580 №2. Работа');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_3_work',2161665234,'zodino_pns.zodino_pns_20','bool','abb_acs580 №3. Работа');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_4_work',2648527978,'zodino_pns.zodino_pns_20','bool','abb_acs580 №4. Работа');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.abb_acs580_5_work',1451329487,'zodino_pns.zodino_pns_20','bool','abb_acs580 №5. Работа');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.system_code',2912250171,'zodino_pns.zodino_pns_20','uint','Системный ответ');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p1_state',3080494436,'zodino_pns.zodino_pns_20','bool','Состояние Н1');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p2_state',2255783929,'zodino_pns.zodino_pns_20','bool','Состояние Н2');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p3_state',537103437,'zodino_pns.zodino_pns_20','bool','Состояние Н3');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p4_state',3852776131,'zodino_pns.zodino_pns_20','bool','Состояние Н4');
INSERT INTO ds_list(id,id_hash,fk_object,type,descr) VALUES('zodino_pns.zodino_pns_20.p5_state',1137949047,'zodino_pns.zodino_pns_20','bool','Состояние Н5');
